### ISSUE TITLE
Opening the zipped radar data

### ISSUE THREAD

**Issue by Nicholas-Autio-Mitchell** [kaist-avelab/K-Radar_V1#14]
Thank you for the wonderful dataset and sharing Google Drive links to download it!

I have noticed there are no instructions on how to unzip/merge the three archives for radar data in each sequence. Take for example sequence 2, there are files `radar_02.z01`, `radar_02.z02` and `radar_02.zip`. The final of those three contains reference to all 628 `*.mat` files contained in the multi-part archive (seen using `unzip -l radar_02.zip`). However, if extracted using `unzip`, only 148 files are obtained (with some warnings about missing data). It seems like it skips `radar_02.z01` and `radar_02.z02`.

I have tried concatenating the three zip files and then opening a single file, but that also fails:

```
$ cat radar_02.z01 radar_02.z02 radar_02.zip > radar_combined_z01_z02_zip.zip
$ unzip radar_combined.zip

Archive:  radar_combined_z01_z02_zip.zip
error: End-of-centdir-64 signature not where expected (prepended bytes?)
  (attempting to process anyway)
warning [radar_combined_z01_z02_zip.zip]:  zipfile claims to be last disk of a multi-part archive;
  attempting to process anyway, assuming all parts have been concatenated
  together in order.  Expect "errors" and warnings...true multi-part support
  doesn't exist yet (coming soon).
warning [radar_combined_z01_z02_zip.zip]:  27917287424 extra bytes at beginning or within zipfile
  (attempting to process anyway)
file #1:  bad zipfile offset (local header sig):  27917287428
  (attempting to re-compensate)
error: invalid zip file with overlapped components (possible zip bomb)
```

-------------------------

[Instructions found in the K-Lanes](https://drive.google.com/drive/folders/12aLITzR_tE8eVi-Q4OWoomX9VR3Olea7) dataset unfortunately **do not work** in this case either:

> To unzip the file in linux system(eg. Ubuntu 20.04)
>
> // sudo apt-get install default-jdk
> // jar xvf (file_you_downloaded).zip

This gives errors (for individual parts **and** the concatenated file from above) such as:

```
 $ ▶ jar xfv radar_combined_z01_z02_zip.zip
java.util.zip.ZipException: invalid CEN header (bad signature)
        at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1607)
        at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1557)
        at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1308)
        at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1271)
        at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:733)
        at java.base/java.util.zip.ZipFile$CleanableResource.get(ZipFile.java:850)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:248)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:177)
        at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
        at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1388)
        at jdk.jartool/sun.tools.jar.Main.run(Main.java:410)
        at jdk.jartool/sun.tools.jar.Main.main(Main.java:1680)
```

Any help would be greatly appreciated :)

**Comment by YoushaaMurhij** [comment]
I have the same problem here. Any updates on this?
